# This compose file provides an example of attaching multiple webviewer-server instances to a single load balancer. Please refer to docker-compose.yml for regular usage.
version: "3.0"
services:
    loadbalancer:
        image: "pdftron/wv-loadbalancer:latest"
        # For providing a SSL key. Mounts the directory named SSL and expects a combined_key.pem to be present.
        # volumes:
        #  - ./ssl/:/etc/ssl/default/
        environment:
            # used if you wish to replace the SSL port with another HTTP port
            # bind '8051' in your ports to use this port
            # effective for a situation where HTTPs is handled by another entrypoint
            DISABLE_SSL: 'false'
            # used if the anonymous annotations feature is being hosted on a server other than
            # the one which processes PDFs
            REROUTE_ANNOT_REQUESTS: 'false'
            INITIAL_NODE_A: pdfd-tomcat
            INITIAL_NODE_B: pdfd-tomcat2
            # Sets a URL prefix for the server
            URL_PREFIX:
            # Enables management from tcp socket 4893
            # Do not enable unless your server is secure from external access
            # Add 4893:4893 to the ports section if using this
            ENABLE_TCP_MANAGEMENT: 'false'
        ports:
            # ssl access
            - 8444:4430
            # non-ssl access
            - "8090:8050"
            # ssh administration access
            - "2223:22"
            # stats page
            - "8999:9001"
            # health check -> localhost:60001/http_health_check
            - 60001:60001
    pdfd-tomcat:
        image: "pdftron/webviewer-server:latest"
        ulimits:
          nofile:
            soft: 64000
            hard: 64000
        environment:
          # More info about these arguments can be found at:
            # https://www.pdftron.com/documentation/web/guides/wv-server-config
            # Place your PDFTron key in this argument.
            TRN_PDFNET_KEY:
            # If set to true, tomcat will include the demo app at localhost:port/demo?s
            INCLUDE_DEMO: 'true'
            # Normally the cache cleanup is triggered once there is less than 1Gb 
            # of space remaining on the partition, at which point files that have
            # not been accessed recently are wiped from the cache.
            # The following two settings override this behaviour.
            #
            # Any file that has not been touched within this number of minutes
            # will be wiped from the local disk cache. Cannot be smaller than 10.
            # A value of 0 is ignored entirely
            TRN_MAX_CACHE_AGE_MINUTES: 0
            # Cached content will be cleaned up until the cache occupies less space
            # than this limit
            # Cannot be smaller than 200, and a value of 0 is ignored.
            TRN_MAX_CACHED_MB: 0
            # Control the cookie WebViewer Server checks for user stickiness.
            TRN_BALANCER_COOKIE_NAME: HAPROXID
            TRN_DEBUG_MODE: 'false'
            # Force the server to fetch any incoming request at this argument + the incoming link.
            # TRN_FETCH_DEFAULT_BASE_ADDR: www.mywebsite.com
            # Set required domains for document fetches
            # TRN_FETCH_REQUIRED_URL_ROOT: "www.doc.com;www.pdf.com;www.download.com"
            # Forward same domain cookies between servers on file fetches.
            # TRN_FORWARD_CLIENT_COOKIES: 'false'
            # Lock documents to a user session.
            # TRN_ENABLE_SESSION_AUTH: 'false'
            # Cache documents behind a session id identifier.
            # TRN_ENABLE_PER_SESSION_CACHING: 'false'
            # Prevent the server from sending the client PDF data directly, using
            # derived formats like images or .xod instead
            # TRN_DISABLE_CLIENT_PDF_ACCESS: 'true'
            # Forces all file fetches to be downgraded to http.
            # TRN_FETCH_DOWNGRADE_HTTPS: 'false'
        # uncomment to map the static data directory to a drive outside the container
        # just replace my_external_static_data with the desired externally mapped folder.
        #volumes:
        #  - ./my_external_static_data:/usr/local/apache-tomcat/static_data
        ports:
            # Sets the port to bind the internal 8090 port to. Follows the pattern
            # external:internal (80:8090). Internal port must either be 8090 or 8443.
            - 8060:8090
    pdfd-tomcat2:
        image: "pdftron/webviewer-server:latest"
        ulimits:
          nofile:
            soft: 64000
            hard: 64000
        environment:
            # More info about these arguments can be found at:
            # https://www.pdftron.com/documentation/web/guides/wv-server-config
            # Place your PDFTron key in this argument.
            TRN_PDFNET_KEY:
            # If set to true, tomcat will include the demo app at localhost:port/demo?s
            INCLUDE_DEMO: 'true'
            # Normally the cache cleanup is triggered once there is less than 1Gb 
            # of space remaining on the partition, at which point files that have
            # not been accessed recently are wiped from the cache.
            # The following two settings override this behaviour.
            #
            # Any file that has not been touched within this number of minutes
            # will be wiped from the local disk cache. Cannot be smaller than 10.
            # A value of 0 is ignored entirely
            TRN_MAX_CACHE_AGE_MINUTES: 0
            # Cached content will be cleaned up until the cache occupies less space
            # than this limit
            # Cannot be smaller than 200, and a value of 0 is ignored.
            TRN_MAX_CACHED_MB: 0
            # Control the cookie WebViewer Server checks for user stickiness.
            TRN_BALANCER_COOKIE_NAME: HAPROXID
            TRN_DEBUG_MODE: 'false'
            # Force the server to fetch any incoming request at this argument + the incoming link.
            # TRN_FETCH_DEFAULT_BASE_ADDR: www.mywebsite.com
            # Set required domains for document fetches
            # TRN_FETCH_REQUIRED_URL_ROOT: "www.doc.com;www.pdf.com;www.download.com"
            # Forward same domain cookies between servers on file fetches.
            # TRN_FORWARD_CLIENT_COOKIES: 'false'
            # Lock documents to a user session.
            # TRN_ENABLE_SESSION_AUTH: 'false'
            # Cache documents behind a session id identifier.
            # TRN_ENABLE_PER_SESSION_CACHING: 'false'
            # Prevent the server from sending the client PDF data directly, using
            # derived formats like images or .xod instead
            # TRN_DISABLE_CLIENT_PDF_ACCESS: 'true'
            # Forces all file fetches to be downgraded to http.
            # TRN_FETCH_DOWNGRADE_HTTPS: 'false'
        # uncomment to map the static data directory to a drive outside the container
        # just replace my_external_static_data with the desired externally mapped folder.
        #volumes:
        #  - ./my_external_static_data:/usr/local/apache-tomcat/static_data
        ports:
            # Sets the port to bind the internal 8090 port to. Follows the pattern
            # external:internal (80:8090). Internal port must either be 8090 or 8443.
            - 8070:8090

